-- create table from databricks
CREATE TABLE cisco_asa_logs (
  _tp_time TIMESTAMP,
  message STRING,
  log_level STRING,
  message_id STRING,
  vendor STRING,
  product STRING,
  vendor_product STRING,
  action STRING,
  vendor_action STRING,
  status STRING,
  transport STRING,
  protocol STRING,
  communication_protocol STRING,
  direction STRING,
  src_interface STRING,
  src_ip STRING,
  src_host STRING,
  src_port STRING,
  src_user STRING,
  src_nt_domain STRING,
  dest_interface STRING,
  dest_ip STRING,
  dest_host STRING,
  dest_port STRING,
  dest_user STRING,
  dest_nt_domain STRING,
  dest_public_ip STRING,
  dest_public_port STRING,
  user STRING,
  username STRING,
  group_name STRING,
  session_id STRING,
  duration BIGINT,
  bytes BIGINT,
  bytes_in STRING,
  bytes_out STRING,
  rule STRING,
  rule_id STRING,
  rule_name STRING,
  acl STRING,
  access_group STRING,
  icmp_type STRING,
  icmp_code STRING,
  assigned_ipv4 STRING,
  assigned_ip STRING,
  app STRING,
  category STRING,
  severity STRING,
  vendor_severity STRING,
  type STRING,
  signature STRING,
  signature_id STRING,
  object STRING,
  object_category STRING,
  command STRING,
  process_name STRING,
  parent_process_name STRING,
  result STRING,
  tcp_flag STRING,
  ip_options STRING,
  attack_type STRING,
  group_policy STRING,
  hash_codes STRING,
  ids_type STRING,
  eventtypes STRING,           -- Changed from ARRAY<STRING> to STRING
  tags STRING,                 -- Changed from ARRAY<STRING> to STRING
  cisco_asa_message_id STRING,
  cisco_asa_user STRING,
  dest_zone STRING,
  src_zone STRING
)
USING DELTA
COMMENT 'Cisco ASA logs final table';

CREATE EXTERNAL STREAM cisco_asa_ta.http_databricks_cisco_asa (
  _tp_time datetime64(3),
  message string,
  log_level string,
  message_id string,
  vendor string,
  product string,
  vendor_product string,
  action string,
  vendor_action string,
  status string,
  transport string,
  protocol string,
  communication_protocol string,
  direction string,
  src_interface string,
  src_ip string,
  src_host string,
  src_port string,
  src_user string,
  src_nt_domain string,
  dest_interface string,
  dest_ip string,
  dest_host string,
  dest_port string,
  dest_user string,
  dest_nt_domain string,
  dest_public_ip string,
  dest_public_port string,
  user string,
  username string,
  group_name string,
  session_id string,
  duration int64,
  bytes int64,
  bytes_in string,
  bytes_out string,
  rule string,
  rule_id string,
  rule_name string,
  acl string,
  access_group string,
  icmp_type string,
  icmp_code string,
  assigned_ipv4 string,
  assigned_ip string,
  app string,
  category string,
  severity string,
  vendor_severity string,
  type string,
  signature string,
  signature_id string,
  object string,
  object_category string,
  command string,
  process_name string,
  parent_process_name string,
  result string,
  tcp_flag string,
  ip_options string,
  attack_type string,
  group_policy string,
  hash_codes string,
  ids_type string,
  eventtypes string,           -- Changed from array(string) to string
  tags string,                 -- Changed from array(string) to string
  cisco_asa_message_id string,
  cisco_asa_user string,
  dest_zone string,
  src_zone string
)
SETTINGS
type = 'http',
http_header_Authorization='Bearer dapi5836e145516129fd2b0577b3520ea84f',
url = 'https://dbc-2d503d01-f996.cloud.databricks.com/api/2.0/sql/statements/',
data_format = 'Template',
format_template_resultset_format='{"warehouse_id":"d638ed416dfa21dc","statement": "INSERT INTO cisco_asa_logs (_tp_time, message, log_level, message_id, vendor, product, vendor_product, action, vendor_action, status, transport, protocol, communication_protocol, direction, src_interface, src_ip, src_host, src_port, src_user, src_nt_domain, dest_interface, dest_ip, dest_host, dest_port, dest_user, dest_nt_domain, dest_public_ip, dest_public_port, user, username, group_name, session_id, duration, bytes, bytes_in, bytes_out, rule, rule_id, rule_name, acl, access_group, icmp_type, icmp_code, assigned_ipv4, assigned_ip, app, category, severity, vendor_severity, type, signature, signature_id, object, object_category, command, process_name, parent_process_name, result, tcp_flag, ip_options, attack_type, group_policy, hash_codes, ids_type, eventtypes, tags, cisco_asa_message_id, cisco_asa_user, dest_zone, src_zone) VALUES (:_tp_time, :message, :log_level, :message_id, :vendor, :product, :vendor_product, :action, :vendor_action, :status, :transport, :protocol, :communication_protocol, :direction, :src_interface, :src_ip, :src_host, :src_port, :src_user, :src_nt_domain, :dest_interface, :dest_ip, :dest_host, :dest_port, :dest_user, :dest_nt_domain, :dest_public_ip, :dest_public_port, :user, :username, :group_name, :session_id, :duration, :bytes, :bytes_in, :bytes_out, :rule, :rule_id, :rule_name, :acl, :access_group, :icmp_type, :icmp_code, :assigned_ipv4, :assigned_ip, :app, :category, :severity, :vendor_severity, :type, :signature, :signature_id, :object, :object_category, :command, :process_name, :parent_process_name, :result, :tcp_flag, :ip_options, :attack_type, :group_policy, :hash_codes, :ids_type, :eventtypes, :tags, :cisco_asa_message_id, :cisco_asa_user, :dest_zone, :src_zone)", "parameters": [${data}]}',
format_template_row_format='{ "name": "_tp_time", "value": ${_tp_time:JSON}, "type": "TIMESTAMP" },{ "name": "message", "value": ${message:JSON}, "type": "STRING" },{ "name": "log_level", "value": ${log_level:JSON}, "type": "STRING" },{ "name": "message_id", "value": ${message_id:JSON}, "type": "STRING" },{ "name": "vendor", "value": ${vendor:JSON}, "type": "STRING" },{ "name": "product", "value": ${product:JSON}, "type": "STRING" },{ "name": "vendor_product", "value": ${vendor_product:JSON}, "type": "STRING" },{ "name": "action", "value": ${action:JSON}, "type": "STRING" },{ "name": "vendor_action", "value": ${vendor_action:JSON}, "type": "STRING" },{ "name": "status", "value": ${status:JSON}, "type": "STRING" },{ "name": "transport", "value": ${transport:JSON}, "type": "STRING" },{ "name": "protocol", "value": ${protocol:JSON}, "type": "STRING" },{ "name": "communication_protocol", "value": ${communication_protocol:JSON}, "type": "STRING" },{ "name": "direction", "value": ${direction:JSON}, "type": "STRING" },{ "name": "src_interface", "value": ${src_interface:JSON}, "type": "STRING" },{ "name": "src_ip", "value": ${src_ip:JSON}, "type": "STRING" },{ "name": "src_host", "value": ${src_host:JSON}, "type": "STRING" },{ "name": "src_port", "value": ${src_port:JSON}, "type": "STRING" },{ "name": "src_user", "value": ${src_user:JSON}, "type": "STRING" },{ "name": "src_nt_domain", "value": ${src_nt_domain:JSON}, "type": "STRING" },{ "name": "dest_interface", "value": ${dest_interface:JSON}, "type": "STRING" },{ "name": "dest_ip", "value": ${dest_ip:JSON}, "type": "STRING" },{ "name": "dest_host", "value": ${dest_host:JSON}, "type": "STRING" },{ "name": "dest_port", "value": ${dest_port:JSON}, "type": "STRING" },{ "name": "dest_user", "value": ${dest_user:JSON}, "type": "STRING" },{ "name": "dest_nt_domain", "value": ${dest_nt_domain:JSON}, "type": "STRING" },{ "name": "dest_public_ip", "value": ${dest_public_ip:JSON}, "type": "STRING" },{ "name": "dest_public_port", "value": ${dest_public_port:JSON}, "type": "STRING" },{ "name": "user", "value": ${user:JSON}, "type": "STRING" },{ "name": "username", "value": ${username:JSON}, "type": "STRING" },{ "name": "group_name", "value": ${group_name:JSON}, "type": "STRING" },{ "name": "session_id", "value": ${session_id:JSON}, "type": "STRING" },{ "name": "duration", "value": ${duration:JSON}, "type": "BIGINT" },{ "name": "bytes", "value": ${bytes:JSON}, "type": "BIGINT" },{ "name": "bytes_in", "value": ${bytes_in:JSON}, "type": "STRING" },{ "name": "bytes_out", "value": ${bytes_out:JSON}, "type": "STRING" },{ "name": "rule", "value": ${rule:JSON}, "type": "STRING" },{ "name": "rule_id", "value": ${rule_id:JSON}, "type": "STRING" },{ "name": "rule_name", "value": ${rule_name:JSON}, "type": "STRING" },{ "name": "acl", "value": ${acl:JSON}, "type": "STRING" },{ "name": "access_group", "value": ${access_group:JSON}, "type": "STRING" },{ "name": "icmp_type", "value": ${icmp_type:JSON}, "type": "STRING" },{ "name": "icmp_code", "value": ${icmp_code:JSON}, "type": "STRING" },{ "name": "assigned_ipv4", "value": ${assigned_ipv4:JSON}, "type": "STRING" },{ "name": "assigned_ip", "value": ${assigned_ip:JSON}, "type": "STRING" },{ "name": "app", "value": ${app:JSON}, "type": "STRING" },{ "name": "category", "value": ${category:JSON}, "type": "STRING" },{ "name": "severity", "value": ${severity:JSON}, "type": "STRING" },{ "name": "vendor_severity", "value": ${vendor_severity:JSON}, "type": "STRING" },{ "name": "type", "value": ${type:JSON}, "type": "STRING" },{ "name": "signature", "value": ${signature:JSON}, "type": "STRING" },{ "name": "signature_id", "value": ${signature_id:JSON}, "type": "STRING" },{ "name": "object", "value": ${object:JSON}, "type": "STRING" },{ "name": "object_category", "value": ${object_category:JSON}, "type": "STRING" },{ "name": "command", "value": ${command:JSON}, "type": "STRING" },{ "name": "process_name", "value": ${process_name:JSON}, "type": "STRING" },{ "name": "parent_process_name", "value": ${parent_process_name:JSON}, "type": "STRING" },{ "name": "result", "value": ${result:JSON}, "type": "STRING" },{ "name": "tcp_flag", "value": ${tcp_flag:JSON}, "type": "STRING" },{ "name": "ip_options", "value": ${ip_options:JSON}, "type": "STRING" },{ "name": "attack_type", "value": ${attack_type:JSON}, "type": "STRING" },{ "name": "group_policy", "value": ${group_policy:JSON}, "type": "STRING" },{ "name": "hash_codes", "value": ${hash_codes:JSON}, "type": "STRING" },{ "name": "ids_type", "value": ${ids_type:JSON}, "type": "STRING" },{ "name": "eventtypes", "value": ${eventtypes:JSON}, "type": "STRING" },{ "name": "tags", "value": ${tags:JSON}, "type": "STRING" },{ "name": "cisco_asa_message_id", "value": ${cisco_asa_message_id:JSON}, "type": "STRING" },{ "name": "cisco_asa_user", "value": ${cisco_asa_user:JSON}, "type": "STRING" },{ "name": "dest_zone", "value": ${dest_zone:JSON}, "type": "STRING" },{ "name": "src_zone", "value": ${src_zone:JSON}, "type": "STRING" }',
format_template_rows_between_delimiter='',
one_message_per_row=true;


INSERT INTO cisco_asa_ta.http_databricks_cisco_asa (
  _tp_time, message, log_level, message_id, vendor, product, vendor_product, action,
  vendor_action, status, transport, protocol, communication_protocol, direction,
  src_interface, src_ip, src_host, src_port, src_user, src_nt_domain,
  dest_interface, dest_ip, dest_host, dest_port, dest_user, dest_nt_domain,
  dest_public_ip, dest_public_port, user, username, group_name, session_id,
  duration, bytes, bytes_in, bytes_out, rule, rule_id, rule_name, acl, access_group,
  icmp_type, icmp_code, assigned_ipv4, assigned_ip, app, category,
  severity, vendor_severity, type, signature, signature_id, object, object_category,
  command, process_name, parent_process_name, result, tcp_flag, ip_options,
  attack_type, group_policy, hash_codes, ids_type, eventtypes, tags,
  cisco_asa_message_id, cisco_asa_user, dest_zone, src_zone
)
SELECT 
  _tp_time,
  message,
  log_level,
  message_id,
  vendor,
  product,
  vendor_product,
  action,
  COALESCE(vendor_action, ''),
  COALESCE(status, ''),
  COALESCE(transport, ''),
  COALESCE(protocol, ''),
  COALESCE(communication_protocol, ''),
  COALESCE(direction, ''),
  COALESCE(src_interface, ''),
  COALESCE(src_ip, ''),
  COALESCE(src_host, ''),
  COALESCE(src_port, ''),
  COALESCE(src_user, ''),
  COALESCE(src_nt_domain, ''),
  COALESCE(dest_interface, ''),
  COALESCE(dest_ip, ''),
  COALESCE(dest_host, ''),
  COALESCE(dest_port, ''),
  COALESCE(dest_user, ''),
  COALESCE(dest_nt_domain, ''),
  COALESCE(dest_public_ip, ''),
  COALESCE(dest_public_port, ''),
  COALESCE(user, ''),
  COALESCE(username, ''),
  COALESCE(group_name, ''),
  COALESCE(session_id, ''),
  COALESCE(duration, 0),
  COALESCE(bytes, 0),
  COALESCE(bytes_in, ''),
  COALESCE(bytes_out, ''),
  COALESCE(rule, ''),
  COALESCE(rule_id, ''),
  COALESCE(rule_name, ''),
  COALESCE(acl, ''),
  COALESCE(access_group, ''),
  COALESCE(icmp_type, ''),
  COALESCE(icmp_code, ''),
  COALESCE(assigned_ipv4, ''),
  COALESCE(assigned_ip, ''),
  COALESCE(app, ''),
  COALESCE(category, ''),
  severity,
  vendor_severity,
  COALESCE(type, ''),
  COALESCE(signature, ''),
  COALESCE(signature_id, ''),
  COALESCE(object, ''),
  COALESCE(object_category, ''),
  COALESCE(command, ''),
  COALESCE(process_name, ''),
  COALESCE(parent_process_name, ''),
  COALESCE(result, ''),
  COALESCE(tcp_flag, ''),
  COALESCE(ip_options, ''),
  COALESCE(attack_type, ''),
  COALESCE(group_policy, ''),
  COALESCE(hash_codes, ''),
  ids_type,
  to_json_string(eventtypes),
  to_json_string(tags),
  cisco_asa_message_id,
  COALESCE(cisco_asa_user, ''),
  COALESCE(dest_zone, ''),
  COALESCE(src_zone, '')
FROM cisco_asa_ta.cisco_asa_logs_final limit 1

CREATE MATERIALIZED VIEW cisco_asa_ta.mv_cisco_asa_logs_to_databricks AS
SELECT 
  _tp_time,
  message,
  log_level,
  message_id,
  vendor,
  product,
  vendor_product,
  action,
  COALESCE(vendor_action, ''),
  COALESCE(status, ''),
  COALESCE(transport, ''),
  COALESCE(protocol, ''),
  COALESCE(communication_protocol, ''),
  COALESCE(direction, ''),
  COALESCE(src_interface, ''),
  COALESCE(src_ip, ''),
  COALESCE(src_host, ''),
  COALESCE(src_port, ''),
  COALESCE(src_user, ''),
  COALESCE(src_nt_domain, ''),
  COALESCE(dest_interface, ''),
  COALESCE(dest_ip, ''),
  COALESCE(dest_host, ''),
  COALESCE(dest_port, ''),
  COALESCE(dest_user, ''),
  COALESCE(dest_nt_domain, ''),
  COALESCE(dest_public_ip, ''),
  COALESCE(dest_public_port, ''),
  COALESCE(user, ''),
  COALESCE(username, ''),
  COALESCE(group_name, ''),
  COALESCE(session_id, ''),
  COALESCE(duration, 0),
  COALESCE(bytes, 0),
  COALESCE(bytes_in, ''),
  COALESCE(bytes_out, ''),
  COALESCE(rule, ''),
  COALESCE(rule_id, ''),
  COALESCE(rule_name, ''),
  COALESCE(acl, ''),
  COALESCE(access_group, ''),
  COALESCE(icmp_type, ''),
  COALESCE(icmp_code, ''),
  COALESCE(assigned_ipv4, ''),
  COALESCE(assigned_ip, ''),
  COALESCE(app, ''),
  COALESCE(category, ''),
  severity,
  vendor_severity,
  COALESCE(type, ''),
  COALESCE(signature, ''),
  COALESCE(signature_id, ''),
  COALESCE(object, ''),
  COALESCE(object_category, ''),
  COALESCE(command, ''),
  COALESCE(process_name, ''),
  COALESCE(parent_process_name, ''),
  COALESCE(result, ''),
  COALESCE(tcp_flag, ''),
  COALESCE(ip_options, ''),
  COALESCE(attack_type, ''),
  COALESCE(group_policy, ''),
  COALESCE(hash_codes, ''),
  ids_type,
  to_json_string(eventtypes),
  to_json_string(tags),
  cisco_asa_message_id,
  COALESCE(cisco_asa_user, ''),
  COALESCE(dest_zone, ''),
  COALESCE(src_zone, '')
FROM cisco_asa_ta.cisco_asa_logs_final
SETTINGS max_insert_block_size=1, max_block_size=1;