apiVersion: apps/v1
kind: Deployment
metadata:
  name: marimo-app
  namespace: marimo
  labels:
    app: marimo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marimo
  template:
    metadata:
      labels:
        app: marimo
    spec:
      containers:
      - name: marimo-app
        # Replace with your actual image URL
        image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/marimo-repo/marimo-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MARIMO_HOST
          value: "0.0.0.0"
        - name: MARIMO_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: marimo-service
  namespace: marimo
  labels:
    app: marimo
spec:
  type: LoadBalancer
  selector:
    app: marimo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: ClientIP