apiVersion: v1
kind: Service
metadata:
  name: splunk-hec
  namespace: splunk-operator
spec:
  type: LoadBalancer
  ports:
  - name: hec
    port: 8088
    targetPort: 8088
    protocol: TCP
  selector:
    app.kubernetes.io/component: standalone
    app.kubernetes.io/instance: splunk-single-standalone
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: standalone
    app.kubernetes.io/part-of: splunk-single-standalone