apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: single
  namespace: splunk-operator
spec:
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageClassName: standard-rwo
    storageCapacity: 10Gi
  varVolumeStorageConfig:
    storageClassName: standard-rwo
    storageCapacity: 100Gi