{
 "title": "Real-time Observability",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "sql": "select _tp_time,instance,metrics_value from(\n  select _tp_time, array_join(raw:resourceMetrics[*]) as rm\n,(array_filter(x -> x:key = 'host.name' or x:key = 'instance', rm:resource.attributes[*])[1]):value.stringValue as instance,rm:scopeMetrics[*][1] as sm,\nreplace_regex(sm:scope.name,'.*scraper/(.*)','\\\\1') as scope_name\n,array_join(sm:metrics[*]) as metrics,metrics:description as metrics_desc\n,(metrics:gauge.dataPoints[*][1]):asDouble::double as metrics_value\nfrom o11y.otlp_metrics where _tp_time < to_datetime($__to/1000) and _tp_time > to_datetime($__from/1000) and scope_name='loadscraper' and metrics_desc='Average CPU Load over 1 minute.' \n);"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "sql": "select _tp_time,instance,metrics_value from(\n  select _tp_time, array_join(raw:resourceMetrics[*]) as rm\n,(array_filter(x -> x:key = 'host.name' or x:key = 'instance', rm:resource.attributes[*])[1]):value.stringValue as instance,rm:scopeMetrics[*][1] as sm,\nreplace_regex(sm:scope.name,'.*scraper/(.*)','\\\\1') as scope_name\n,array_join(sm:metrics[*]) as metrics,metrics:description as metrics_desc\n,(metrics:sum.dataPoints[*][1]):asInt::uint32 as metrics_value\nfrom o11y.otlp_metrics where _tp_time < to_datetime($__to/1000) and _tp_time > to_datetime($__from/1000) and scope_name='memoryscraper' and metrics_desc='Bytes of memory in use.'\n);"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "sql": "\nselect _tp_time,instance,metrics_value from(\n  select _tp_time, array_join(raw:resourceMetrics[*]) as rm\n,(array_filter(x -> x:key = 'host.name' or x:key = 'instance', rm:resource.attributes[*])[1]):value.stringValue as instance,rm:scopeMetrics[*][1] as sm,\nreplace_regex(sm:scope.name,'.*scraper/(.*)','\\\\1') as scope_name\n,array_join(sm:metrics[*]) as metrics,metrics:description as metrics_desc\n,(metrics:sum.dataPoints[*][1]):asInt::uint64 as metrics_value\nfrom o11y.otlp_metrics where _tp_time < to_datetime($__to/1000) and _tp_time > to_datetime($__from/1000) and scope_name='filesystemscraper' and metrics_desc='Filesystem bytes used.'\n);"
    }
   ]
  }
 ]
}